version: "3"
services:
  db:
    image: mysql:latest
    container_name: my_app_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_app
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -uroot -ppassword
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "3306:3306"
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    command: bash -c "bundle install && bundle exec rails db:prepare && rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - ./back:/app
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - "3000:3000"
    user: "1000:1000"
    depends_on:
      db:
        condition: service_healthy
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    command: bash -c "yarn install && yarn dev -p 8000"
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"
volumes:
  mysql_data:
