FROM --platform=linux/amd64 ruby:3.2.3
ARG UID=1000
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo
ENV BUNDLE_APP_CONFIG /app/.bundle
RUN apt-get update -qq && apt-get install -y build-essential default-mysql-client vim
RUN useradd -m -u $UID user
RUN mkdir /app
WORKDIR /app
COPY . /app
RUN chown -R user:user /app

