# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bootsnap', require: false
gem 'mysql2', '~> 0.5'
gem 'puma', '>= 5.0'
gem 'rack-cors'
gem 'rails', '~> 7.2.1'
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  gem 'annotate'
  gem 'brakeman', require: false
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
end

gem 'active_model_serializers', '~> 0.10.0'
gem 'dotenv-rails'
gem 'dotenv-rails'
gem 'jwt'
gem 'omniauth'
gem 'omniauth-github', '~> 2.0.0'
gem 'omniauth-rails_csrf_protection'
gem 'rails_same_site_cookie'
