source "https://rubygems.org"

gem "rails", "~> 7.2.1"
gem "mysql2", "~> 0.5"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "rack-cors"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem 'rubocop', require: false
end

gem 'dotenv-rails'
gem 'rails_same_site_cookie'
gem 'omniauth'
gem 'omniauth-github', '~> 2.0.0'
gem "omniauth-rails_csrf_protection"
gem 'jwt'
gem 'active_model_serializers'
gem 'dotenv-rails'
